Repository php-censor/php-censor, pull requests merged in 2020-10, with the labels that each got.

#378 Adding Bahasa Indonesia
  bootstrap.php
  src/Languages/lang.id.php
Labels: component:localization, priority:minor, type:enhancement

#379 Fixed SQLite plugin PDO initialization. Issue #377.
  src/Plugin/Sqlite.php
Labels: component:plugin, priority:major, type:bug

#380 Added variable for interpolation APP_VERSION (%APP_VERSION%).
  docs/en/interpolation.md
  src/Builder.php
  src/Helper/BuildInterpolator.php
  src/Plugin/WebhookNotify.php
  tests/src/Helper/BuildInterpolatorTest.php
  tests/src/PluginTest.php
Labels: component:common, priority:minor, type:feature

#381 Improved PHP Censor version variable
  docs/en/interpolation.md
  src/Builder.php
  src/Console/Application.php
  src/Helper/BuildInterpolator.php
  src/Plugin/Campfire.php
  src/Plugin/HipchatNotify.php
  src/Plugin/WebhookNotify.php
  src/WebController.php
Labels: component:common, priority:minor, type:enhancement

#392 Adding Bahase Malaysia
  src/Languages/lang.my.php
Labels: component:localization, priority:minor, type:enhancement

#393 Update More Malaysian translations
  src/Languages/lang.my.php
Labels: component:localization, priority:minor, type:enhancement
